baseURL = 'https://blog.hostthis.tech/'
languageCode = 'en-us'
title = 'Blog.HostThis.Tech'
theme='archie'
copyright = "Â© Blog.hostthis.tech"
publishDir = "public"
pygmentsstyle = "native" # onedark, native, xcode, dracula, obsidian, gruvbox, xcode-dark, github-dark
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
[params]
	mode="toggle"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3
